/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: MCTav1sh (https://sketchfab.com/MCTav1sh)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ppsh-41-tactical-d7d785b781a94df5b9a4956f64bc3e93
Title: PPSH-41 TACTICAL
*/

import { CustomizerProps } from '@/pages/Separate/Customizer/Customizer';
import { state } from '@/stores/customizerProxy';
import { Weapon } from '@/types/types';
import { router } from '@inertiajs/react';
import { CameraControls, Stage, TransformControls, useGLTF } from '@react-three/drei';
import { JSX, RefObject, useEffect, useMemo, useRef, useState } from 'react';
import * as THREE from 'three';
import { GLTF } from 'three-stdlib';
import { useSnapshot } from 'valtio';
import { addSingleMeshToSelection, changeMeshSelection } from '../Editor/helpers';

type GLTFResult = GLTF & {
    nodes: Record<string, THREE.Mesh>;
    materials: {
        perst: THREE.MeshStandardMaterial;
        material_12: THREE.MeshStandardMaterial;
        ammo: THREE.MeshStandardMaterial;
        mag_35: THREE.MeshPhysicalMaterial;
        scope: THREE.MeshStandardMaterial;
        linza: THREE.MeshPhysicalMaterial;
        material: THREE.MeshStandardMaterial;
        text_set: THREE.MeshPhysicalMaterial;
        text_set3: THREE.MeshStandardMaterial;
        text_set2: THREE.MeshPhysicalMaterial;
        text_set1: THREE.MeshPhysicalMaterial;
        texture_set2: THREE.MeshPhysicalMaterial;
        texture_set1: THREE.MeshPhysicalMaterial;
    };
};

type ModelProps = JSX.IntrinsicElements['group'] & {
    weapon: Weapon;
    cameraControlsRef: RefObject<CameraControls | null>;
    attachmentModels: CustomizerProps['attachmentModels'];
    areaDisplays: CustomizerProps['areaDisplays'];
    restTransforms: CustomizerProps['restTransforms'];
};

type WorldNode = {
    uuid: string;
    geometry: THREE.BufferGeometry;
    material: THREE.Material | THREE.Material[];
    position: [number, number, number];
    rotation: [number, number, number];
    scale: [number, number, number];
    visible: boolean;
};

type TransformSnapshot = {
    object: THREE.Object3D;
    position: THREE.Vector3;
    quaternion: THREE.Quaternion;
    scale: THREE.Vector3;
};

const isTypingTarget = (e: KeyboardEvent) =>
    e.target instanceof HTMLElement && (['INPUT', 'TEXTAREA', 'SELECT'].includes(e.target.tagName) || e.target.isContentEditable);

export default function Model({ cameraControlsRef, weapon, attachmentModels, restTransforms, ...props }: ModelProps) {
    const { nodes, materials, scene } = useGLTF(`/3DModels/${weapon.name}/Main/scene.gltf`) as unknown as GLTFResult;

    const meshRefs = useRef<Record<string, THREE.Mesh | null>>({});
    const sceneGroupRef = useRef<THREE.Group>(null);
    const selectionGroupRef = useRef<THREE.Group>(null);

    useEffect(() => {
        if (Object.keys(attachmentModels ?? {}).length === 0 && Object.keys(nodes).length > 0) {
            router.post('/sendAttachmentModelHierarchy', {
                weapon_id: weapon.id,
                attachment_ids: null,
                model_names: Object.keys(nodes),
            });
            state.dbAttachmentsToMaterialsObject = { UNASSIGNED: Object.keys(nodes) };
            return;
        }
        state.dbAttachmentsToMaterialsObject = attachmentModels;
    }, [attachmentModels, nodes, weapon.id]);

    const worldNodes = useMemo(() => {
        scene.updateMatrixWorld(true);
        return Object.entries(nodes).reduce(
            (acc, [nodeName, n]) => {
                const pos = new THREE.Vector3();
                const scale = new THREE.Vector3();
                const quat = new THREE.Quaternion();
                const euler = new THREE.Euler();
                n.getWorldPosition(pos);
                n.getWorldScale(scale);
                n.getWorldQuaternion(quat);
                euler.setFromQuaternion(quat, 'XYZ');
                acc[nodeName] = {
                    uuid: n.uuid,
                    geometry: n.geometry,
                    material: n.material,
                    position: [pos.x, pos.y, pos.z] as [number, number, number],
                    rotation: [euler.x, euler.y, euler.z] as [number, number, number],
                    scale: [scale.x, scale.y, scale.z] as [number, number, number],
                    visible: 'visible' in n ? n.visible : true,
                };
                return acc;
            },
            {} as Record<string, WorldNode>,
        );
    }, [scene, nodes]);

    useMemo(() => {
        if (materials.material) {
            if (materials.material.normalMap) {
                materials.material.normalScale.set(0.5, 0.5);
            }
            materials.material.roughness = 0.5;
            materials.material.metalness = 0.8;
        }
    }, [materials]);

    useEffect(() => {
        state.nodeNames = Object.keys(worldNodes);
    }, [worldNodes]);

    const snap = useSnapshot(state);
    const initAppliedRef = useRef(false);

    // Hold Ctrl while dragging the gizmo to snap (0.25 units / 15° / 0.1 scale steps).
    const [snapping, setSnapping] = useState(false);

    // Undo/redo for gizmo drags: a snapshot of the dragged object's local transform is
    // pushed on drag start, Ctrl+Z / Ctrl+Shift+Z swap the live transform with the stack.
    const undoStack = useRef<TransformSnapshot[]>([]);
    const redoStack = useRef<TransformSnapshot[]>([]);

    useEffect(() => {
        const captureTransform = (object: THREE.Object3D): TransformSnapshot => ({
            object,
            position: object.position.clone(),
            quaternion: object.quaternion.clone(),
            scale: object.scale.clone(),
        });

        const restoreTransform = (from: RefObject<TransformSnapshot[]>, to: RefObject<TransformSnapshot[]>) => {
            const entry = from.current.pop();
            if (!entry) return;
            to.current.push(captureTransform(entry.object));
            entry.object.position.copy(entry.position);
            entry.object.quaternion.copy(entry.quaternion);
            entry.object.scale.copy(entry.scale);
            entry.object.updateMatrixWorld(true);
        };

        const frameSelection = () => {
            const box = new THREE.Box3();
            state.currentMesh.existingSelection.forEach((name) => {
                const mesh = meshRefs.current[name];
                if (mesh) box.expandByObject(mesh);
            });
            if (box.isEmpty() && sceneGroupRef.current) box.setFromObject(sceneGroupRef.current);
            if (box.isEmpty()) return;
            cameraControlsRef.current?.fitToBox(box, true, { paddingLeft: 0.5, paddingRight: 0.5, paddingTop: 0.5, paddingBottom: 0.5 });
        };

        const handleKeyDown = (e: KeyboardEvent) => {
            if (e.key === 'Control') setSnapping(true);
            if (isTypingTarget(e)) return;
            if (e.ctrlKey && (e.key === 'z' || e.key === 'Z')) {
                e.preventDefault();
                if (e.shiftKey) restoreTransform(redoStack, undoStack);
                else restoreTransform(undoStack, redoStack);
            }
            if (e.ctrlKey && (e.key === 'y' || e.key === 'Y')) {
                e.preventDefault();
                restoreTransform(redoStack, undoStack);
            }
            if (!e.ctrlKey && (e.key === 'f' || e.key === 'F')) frameSelection();
        };
        const handleKeyUp = (e: KeyboardEvent) => {
            if (e.key === 'Control') setSnapping(false);
        };

        window.addEventListener('keydown', handleKeyDown);
        window.addEventListener('keyup', handleKeyUp);
        return () => {
            window.removeEventListener('keydown', handleKeyDown);
            window.removeEventListener('keyup', handleKeyUp);
        };
    }, [cameraControlsRef]);

    const pushUndoSnapshot = () => {
        const target = state.clickedSidebarTab === 1 ? sceneGroupRef.current : selectionGroupRef.current;
        if (!target) return;
        undoStack.current.push({
            object: target,
            position: target.position.clone(),
            quaternion: target.quaternion.clone(),
            scale: target.scale.clone(),
        });
        if (undoStack.current.length > 50) undoStack.current.shift();
        redoStack.current = [];
    };

    useEffect(() => {
        if (!snap.grouped || initAppliedRef.current || !meshRefs.current) return;

        Object.values(snap.dbAttachmentsToMaterialsObject).forEach((nodeNames) => {
            nodeNames.forEach((nodeName) => {
                const n = meshRefs.current[nodeName];
                if (n && 'visible' in n) n.visible = false;
            });
        });

        Object.values(snap.selected).forEach((selAtt) => {
            (state.dbAttachmentsToMaterialsObject[selAtt.name] ?? []).forEach((nodeName) => {
                const n = meshRefs.current[nodeName];
                if (n && 'visible' in n) n.visible = true;
            });
        });

        initAppliedRef.current = true;
    }, [snap.dbAttachmentsToMaterialsObject, snap.grouped, snap.selected]);

    useEffect(() => {
        if (!snap.grouped || !meshRefs.current) return;

        (snap.grouped[state.currentAreaSelection] ?? []).forEach((att) => {
            (state.dbAttachmentsToMaterialsObject[att.name] ?? []).forEach((nodeName) => {
                const n = meshRefs.current[nodeName];
                if (n && 'visible' in n) n.visible = false;
            });
        });

        const currentSelectedMaterialNames = state.dbAttachmentsToMaterialsObject[snap.selected[state.currentAreaSelection]?.name];
        if (!currentSelectedMaterialNames) return;
        currentSelectedMaterialNames.forEach((nodeName) => {
            const n = meshRefs.current[nodeName];
            if (n) n.visible = true;
        });
    }, [nodes, snap.grouped, snap.selected]);

    const HOVER_COLOR = '#ff0000'; // Red for hover
    const SELECTED_COLOR = '#0000ff'; // Blue for selected

    function ensureUniqueMaterial(mesh: THREE.Mesh | undefined) {
        if (!mesh) return;
        if (Array.isArray(mesh.material)) {
            mesh.material = mesh.material.map((m: any) => m.clone());
        } else {
            mesh.material = (mesh.material as any).clone();
        }
    }

    function removeOldSelection() {
        const previousSelection = snap.currentMesh.previousSelection;
        previousSelection.map((nodeName) => {
            const previousMeshRef = meshRefs.current[nodeName];
            if (previousMeshRef) {
                const prevMat = Array.isArray(previousMeshRef.material) ? previousMeshRef.material[0] : previousMeshRef.material;
                if ((prevMat as any)?.color?.isColor && previousMeshRef.userData.__originalColor) {
                    (prevMat as any).color.set(previousMeshRef.userData.__originalColor);
                }
                sceneGroupRef.current!.attach(previousMeshRef);
            }
        });

        state.currentMesh.previousSelection = state.currentMesh.lastSelection;
    }

    function addNewCollection() {
        const nodeNames = snap.currentMesh.existingSelection as typeof state.currentMesh.existingSelection;
        nodeNames.map((nodeName) => {
            if (!nodeName) return;
            const mesh = meshRefs.current[nodeName]!;
            ensureUniqueMaterial(mesh);
            const newMat = Array.isArray(mesh?.material) ? mesh.material[0] : mesh?.material;

            if ((newMat as any)?.color?.isColor && mesh) {
                if (!mesh.userData.__originalColor) {
                    mesh.userData.__originalColor = (newMat as any).color.clone();
                }
                (newMat as any).color.set(SELECTED_COLOR);
            }

            if (mesh && selectionGroupRef.current) {
                selectionGroupRef.current.attach(mesh);
            }
        });

        const box = new THREE.Box3();
        box.makeEmpty();

        snap.currentMesh.existingSelection.forEach((name) => {
            const mesh = meshRefs.current[name];
            if (mesh) {
                box.expandByObject(mesh);
                sceneGroupRef.current!.attach(mesh);
            }
        });

        const center = new THREE.Vector3();
        box.getCenter(center);

        selectionGroupRef.current!.parent?.worldToLocal(center);
        selectionGroupRef.current!.position.copy(center);
        selectionGroupRef.current!.updateMatrixWorld(true);

        snap.currentMesh.existingSelection.forEach((name) => {
            const mesh = meshRefs.current[name];
            if (mesh) selectionGroupRef.current!.attach(mesh);
        });
    }

    useEffect(() => {
        if (!meshRefs.current || !sceneGroupRef.current || !selectionGroupRef.current) return;
        if (snap.action) {
            if (snap.action === 'CHANGESELECTION') {
                removeOldSelection();
                addNewCollection();
            }
            if (snap.action === 'ADDSINGLE') {
                addNewCollection();
            }
        }
        state.action = null;
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [snap.lastUpdateId]);

    // Normalize the saved rest transform into stable array references. Passed declaratively
    // (so <Stage> frames the transformed model at mount), but memoized so re-renders during
    // a gizmo drag don't re-apply them and fling the model out of view.
    // Values must be coerced: MySQL decimal columns arrive as strings ("0.750"), and a
    // string position makes TransformControls' position.add() concatenate instead of add,
    // producing NaN matrices that make the model vanish on the first gizmo drag.
    const rest = useMemo(() => {
        const num = (v: number | undefined, fallback: number) => {
            const n = Number(v);
            return Number.isFinite(n) ? n : fallback;
        };
        return {
            position: [num(restTransforms?.position_x, 0), num(restTransforms?.position_y, 0), num(restTransforms?.position_z, 0)] as [
                number,
                number,
                number,
            ],
            rotation: [num(restTransforms?.rotation_x, 0), num(restTransforms?.rotation_y, 0), num(restTransforms?.rotation_z, 0)] as [
                number,
                number,
                number,
            ],
            scale: [num(restTransforms?.scale_x, 1), num(restTransforms?.scale_y, 1), num(restTransforms?.scale_z, 1)] as [number, number, number],
        };
    }, [
        restTransforms?.position_x,
        restTransforms?.position_y,
        restTransforms?.position_z,
        restTransforms?.rotation_x,
        restTransforms?.rotation_y,
        restTransforms?.rotation_z,
        restTransforms?.scale_x,
        restTransforms?.scale_y,
        restTransforms?.scale_z,
    ]);

    useEffect(() => {
        if (!sceneGroupRef.current || snap.lastApplyIndex === 0) return;
        const newRestTransforms = {
            position_x: sceneGroupRef.current.position.x,
            position_y: sceneGroupRef.current.position.y,
            position_z: sceneGroupRef.current.position.z,
            rotation_x: sceneGroupRef.current.rotation.x,
            rotation_y: sceneGroupRef.current.rotation.y,
            rotation_z: sceneGroupRef.current.rotation.z,
            scale_x: sceneGroupRef.current.scale.x,
            scale_y: sceneGroupRef.current.scale.y,
            scale_z: sceneGroupRef.current.scale.z,
        } as typeof restTransforms;

        router.post('/overwriteAttachmentModelHierarchy', {
            dbAttachmentsToMaterialsObject: JSON.stringify(snap.dbAttachmentsToMaterialsObject),
            weapon_id: weapon.id,
            rest_transforms: newRestTransforms,
        });
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [snap.lastApplyIndex]);

    return (
        <>
            <Stage environment="studio" intensity={0.2} castShadow={true} shadows preset="upfront">
                <group>
                    <CameraControls
                        enabled={snap.cameraControlsEnabled}
                        ref={cameraControlsRef}
                        minDistance={2}
                        maxDistance={7}
                        minPolarAngle={Math.PI / 6}
                        maxPolarAngle={Math.PI / 1.8}
                        onControlEnd={() => handleControlEnd()}
                    />
                    <group {...props} position={rest.position} rotation={rest.rotation} scale={rest.scale} ref={sceneGroupRef}>
                        {Object.entries(worldNodes).map(([nodeName, n]) => (
                            <mesh
                                name={nodeName}
                                ref={(el) => (meshRefs.current[nodeName] = el)}
                                key={n.uuid}
                                castShadow
                                receiveShadow
                                position={n.position}
                                rotation={n.rotation}
                                geometry={n.geometry}
                                material={n.material}
                                visible={meshRefs.current[nodeName]?.visible ?? true}
                                scale={n.scale}
                                onDoubleClick={(e) => {
                                    e.stopPropagation();
                                    if (e.shiftKey) {
                                        addSingleMeshToSelection(e.object.name);
                                    } else {
                                        changeMeshSelection([e.object.name]);
                                        state.lastListSearchId++;
                                    }
                                }}
                                onPointerEnter={(e) => {
                                    e.stopPropagation();
                                    const mesh = e.object as THREE.Mesh;
                                    ensureUniqueMaterial(mesh);
                                    const mat = Array.isArray(mesh.material) ? mesh.material[0] : mesh.material;
                                    if (!mesh.userData.__originalColor) {
                                        mesh.userData.__originalColor = (mat as any).color.clone();
                                    }
                                    (mat as any).color.set(HOVER_COLOR);
                                    if (typeof document !== 'undefined') document.body.style.cursor = 'pointer';
                                }}
                                onPointerLeave={(e) => {
                                    const mesh = e.object as THREE.Mesh;
                                    const mat = Array.isArray(mesh.material) ? mesh.material[0] : mesh.material;
                                    const original: THREE.Color | undefined = mesh.userData.__originalColor;

                                    if (snap.currentMesh.existingSelection.includes(mesh.name)) {
                                        (mat as any).color.set(SELECTED_COLOR);
                                    } else if (original) {
                                        (mat as any).color.copy(original);
                                    }

                                    if (typeof document !== 'undefined') document.body.style.cursor = 'auto';
                                }}
                            />
                        ))}
                    </group>
                </group>
                <group ref={selectionGroupRef}></group>
            </Stage>
            {snap.mode && (
                <TransformControls
                    object={(snap.clickedSidebarTab === 1 ? sceneGroupRef.current : selectionGroupRef.current) ?? undefined}
                    mode={snap.mode}
                    translationSnap={snapping ? 0.25 : null}
                    rotationSnap={snapping ? Math.PI / 12 : null}
                    scaleSnap={snapping ? 0.1 : null}
                    onMouseDown={() => {
                        state.cameraControlsEnabled = false;
                        pushUndoSnapshot();
                    }}
                    onMouseUp={() => (state.cameraControlsEnabled = true)}
                />
            )}
        </>
    );
}

function handleControlEnd(): void {
    state.currentAreaSelection = 'other';
}

useGLTF.preload('/3DModels/PPSH41/scene.gltf');
