/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: MCTav1sh (https://sketchfab.com/MCTav1sh)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ppsh-41-tactical-d7d785b781a94df5b9a4956f64bc3e93
Title: PPSH-41 TACTICAL
*/

import { state } from '@/stores/customizerProxy';
import { Weapon } from '@/types/types';
import { router } from '@inertiajs/react';
import { CameraControls, Stage, TransformControls, useGLTF } from '@react-three/drei';
import { JSX, RefObject, useEffect, useMemo, useRef } from 'react';
import * as THREE from 'three';
import { GLTF } from 'three-stdlib';
import { useSnapshot } from 'valtio';

type GLTFResult = GLTF & {
    nodes: Record<string, THREE.Mesh>;
    materials: {
        perst: THREE.MeshStandardMaterial;
        material_12: THREE.MeshStandardMaterial;
        ammo: THREE.MeshStandardMaterial;
        mag_35: THREE.MeshPhysicalMaterial;
        scope: THREE.MeshStandardMaterial;
        linza: THREE.MeshPhysicalMaterial;
        material: THREE.MeshStandardMaterial;
        text_set: THREE.MeshPhysicalMaterial;
        text_set3: THREE.MeshStandardMaterial;
        text_set2: THREE.MeshPhysicalMaterial;
        text_set1: THREE.MeshPhysicalMaterial;
        texture_set2: THREE.MeshPhysicalMaterial;
        texture_set1: THREE.MeshPhysicalMaterial;
    };
};

type ModelProps = JSX.IntrinsicElements['group'] & {
    weapon: Weapon;
    cameraControlsRef: RefObject<CameraControls>;
};

type WorldNode = {
    uuid: string;
    geometry: THREE.BufferGeometry;
    material: THREE.Material | THREE.Material[];
    position: [number, number, number];
    rotation: [number, number, number];
    scale: [number, number, number];
    visible: boolean;
};

export default function Model({ cameraControlsRef, weapon, attachmentModels, areaDisplays, ...props }: ModelProps) {
    const { nodes, materials, scene } = useGLTF(`/3DModels/${weapon.name}/scene.glb`) as unknown as GLTFResult;

    const meshRefs = useRef<Record<string, THREE.Mesh | null>>({});
    const sceneGroupRef = useRef<THREE.Group>(null);
    const selectionGroupRef = useRef<THREE.Group>(null);

    useEffect(() => {
        if (attachmentModels?.length === 0 && Object.keys(nodes).length > 0) {
            router.post('/sendAttachmentModelHierarchy', {
                weapon_id: weapon.id,
                attachment_ids: null,
                model_names: Object.keys(nodes),
            });
            state.dbAttachmentsToMaterialsObject = { 'Uncategorized Models': Object.keys(nodes) };
            return;
        }
        state.dbAttachmentsToMaterialsObject = attachmentModels;
    }, [attachmentModels, nodes, weapon.id]);

    const worldNodes = useMemo(() => {
        scene.updateMatrixWorld(true);
        return Object.entries(nodes).reduce(
            (acc, [nodeName, n]) => {
                const pos = new THREE.Vector3();
                const scale = new THREE.Vector3();
                const quat = new THREE.Quaternion();
                const euler = new THREE.Euler();
                n.getWorldPosition(pos);
                n.getWorldScale(scale);
                n.getWorldQuaternion(quat);
                euler.setFromQuaternion(quat, 'XYZ');
                acc[nodeName] = {
                    uuid: n.uuid,
                    geometry: n.geometry,
                    material: n.material,
                    position: [pos.x, pos.y, pos.z] as [number, number, number],
                    rotation: [euler.x, euler.y, euler.z] as [number, number, number],
                    scale: [scale.x, scale.y, scale.z] as [number, number, number],
                    visible: 'visible' in n ? n.visible : true,
                };
                return acc;
            },
            {} as Record<string, WorldNode>,
        );
    }, [scene, nodes]);

    useMemo(() => {
        if (materials.material) {
            if (materials.material.normalMap) {
                materials.material.normalScale.set(0.5, 0.5);
            }
            materials.material.roughness = 0.5;
            materials.material.metalness = 0.8;
        }
    }, [materials]);

    useEffect(() => {
        state.nodeNames = Object.keys(worldNodes);
    }, [worldNodes]);

    const snap = useSnapshot(state);
    const initAppliedRef = useRef(false);

    useEffect(() => {
        if (!snap.grouped || initAppliedRef.current || !meshRefs.current) return;

        Object.values(snap.dbAttachmentsToMaterialsObject).forEach((nodeNames) => {
            nodeNames.forEach((nodeName) => {
                const n = meshRefs.current[nodeName];
                if (n && 'visible' in n) n.visible = false;
            });
        });

        Object.values(snap.selected).forEach((selAtt) => {
            (state.dbAttachmentsToMaterialsObject[selAtt.name] ?? []).forEach((nodeName) => {
                const n = meshRefs.current[nodeName];
                if (n && 'visible' in n) n.visible = true;
            });
        });

        initAppliedRef.current = true;
    }, [snap.dbAttachmentsToMaterialsObject, snap.grouped, snap.selected]);

    useEffect(() => {
        if (!snap.grouped || !meshRefs.current) return;

        (snap.grouped[state.currentAreaSelection] ?? []).forEach((att) => {
            (state.dbAttachmentsToMaterialsObject[att.name] ?? []).forEach((nodeName) => {
                const n = meshRefs.current[nodeName];
                if (n && 'visible' in n) n.visible = false;
            });
        });

        const currentSelectedMaterialNames = state.dbAttachmentsToMaterialsObject[snap.selected[state.currentAreaSelection]?.name];
        if (!currentSelectedMaterialNames) return;
        currentSelectedMaterialNames.forEach((nodeName) => {
            const n = meshRefs.current[nodeName];
            if (n) n.visible = true;
        });
    }, [nodes, snap.grouped, snap.selected]);

    const HOVER_COLOR = '#ff0000'; // Red for hover
    const SELECTED_COLOR = '#0000ff'; // Blue for selected

    function ensureUniqueMaterial(mesh: THREE.Mesh | undefined) {
        if (!mesh) return;
        if (Array.isArray(mesh.material)) {
            mesh.material = mesh.material.map((m: any) => m.clone());
        } else {
            mesh.material = (mesh.material as any).clone();
        }
    }

    function removeOldSelection() {
        const previousSelection = snap.currentMesh.previousSelection;
        previousSelection.map((nodeName) => {
            const previousMeshRef = meshRefs.current[nodeName];
            if (previousMeshRef) {
                const prevMat = Array.isArray(previousMeshRef.material) ? previousMeshRef.material[0] : previousMeshRef.material;
                if ((prevMat as any)?.color?.isColor && previousMeshRef.userData.__originalColor) {
                    (prevMat as any).color.set(previousMeshRef.userData.__originalColor);
                }
                sceneGroupRef.current!.attach(previousMeshRef);
            }
        });

        state.currentMesh.previousSelection = state.currentMesh.lastSelection;
    }

    function addNewCollection() {
        const nodeNames = snap.currentMesh.existingSelection as typeof state.currentMesh.existingSelection;
        nodeNames.map((nodeName) => {
            if (!nodeName) return;
            const mesh = meshRefs.current[nodeName]!;
            ensureUniqueMaterial(mesh);
            const newMat = Array.isArray(mesh?.material) ? mesh.material[0] : mesh?.material;

            if ((newMat as any)?.color?.isColor && mesh) {
                if (!mesh.userData.__originalColor) {
                    mesh.userData.__originalColor = (newMat as any).color.clone();
                }
                (newMat as any).color.set(SELECTED_COLOR);
            }

            if (mesh && selectionGroupRef.current) {
                selectionGroupRef.current.attach(mesh);
            }
        });

        const box = new THREE.Box3();
        box.makeEmpty();

        snap.currentMesh.existingSelection.forEach((name) => {
            const mesh = meshRefs.current[name];
            if (mesh) {
                box.expandByObject(mesh);
                sceneGroupRef.current!.attach(mesh);
            }
        });

        const center = new THREE.Vector3();
        box.getCenter(center);

        selectionGroupRef.current!.parent?.worldToLocal(center);
        selectionGroupRef.current!.position.copy(center);
        selectionGroupRef.current!.updateMatrixWorld(true);

        snap.currentMesh.existingSelection.forEach((name) => {
            const mesh = meshRefs.current[name];
            if (mesh) selectionGroupRef.current!.attach(mesh);
        });
    }

    useEffect(() => {
        if (!meshRefs.current || !sceneGroupRef.current || !selectionGroupRef.current) return;
        if (snap.action) {
            if (snap.action === 'CHANGESELECTION') {
                removeOldSelection();
                addNewCollection();
            }
            if (snap.action === 'ADDSINGLE') {
                addNewCollection();
            }
        }
        state.action = null;
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [snap.lastUpdateId]);

    return (
        <>
            <Stage environment="studio" intensity={0.2} castShadow={true} shadows preset="upfront">
                <group>
                    <CameraControls
                        enabled={snap.cameraControlsEnabled}
                        ref={cameraControlsRef}
                        minDistance={2}
                        maxDistance={7}
                        minPolarAngle={Math.PI / 6}
                        maxPolarAngle={Math.PI / 1.8}
                        onControlEnd={() => handleControlEnd()}
                    />
                    <group {...props} dispose={null} rotation={[0, Math.PI / 2, 0]} scale={0.115} position={[0.75, 0.25, 0]}>
                        <group rotation={[0, 0, 0]} ref={sceneGroupRef}>
                            {Object.entries(worldNodes).map(([nodeName, n]) => (
                                <mesh
                                    name={nodeName}
                                    ref={(el) => (meshRefs.current[nodeName] = el)}
                                    key={n.uuid}
                                    castShadow
                                    receiveShadow
                                    position={n.position}
                                    rotation={n.rotation}
                                    geometry={n.geometry}
                                    material={n.material}
                                    visible={meshRefs.current[nodeName]?.visible ?? true}
                                    scale={n.scale}
                                    onDoubleClick={(e) => {
                                        e.stopPropagation();
                                        state.currentMesh.previousSelection = [...state.currentMesh.existingSelection];
                                        if (e.shiftKey) {
                                            state.currentMesh.existingSelection.push(e.object.name);
                                            state.action = 'ADDSINGLE';
                                        } else {
                                            state.currentMesh.existingSelection = [e.object.name];
                                            state.action = 'CHANGESELECTION';
                                            state.lastListSearchId++;
                                        }
                                        state.currentMesh.lastSelection = [e.object.name];
                                        state.lastUpdateId++;
                                    }}
                                    onPointerEnter={(e) => {
                                        e.stopPropagation();
                                        const mesh = e.object as THREE.Mesh;
                                        ensureUniqueMaterial(mesh);
                                        const mat = Array.isArray(mesh.material) ? mesh.material[0] : mesh.material;
                                        if (!mesh.userData.__originalColor) {
                                            mesh.userData.__originalColor = (mat as any).color.clone();
                                        }
                                        (mat as any).color.set(HOVER_COLOR);
                                        if (typeof document !== 'undefined') document.body.style.cursor = 'pointer';
                                    }}
                                    onPointerLeave={(e) => {
                                        const mesh = e.object as THREE.Mesh;
                                        const mat = Array.isArray(mesh.material) ? mesh.material[0] : mesh.material;
                                        const original: THREE.Color | undefined = mesh.userData.__originalColor;

                                        if (snap.currentMesh.existingSelection.includes(mesh.name)) {
                                            (mat as any).color.set(SELECTED_COLOR);
                                        } else if (original) {
                                            (mat as any).color.copy(original);
                                        }

                                        if (typeof document !== 'undefined') document.body.style.cursor = 'auto';
                                    }}
                                />
                            ))}
                        </group>
                    </group>
                </group>
                <group ref={selectionGroupRef}></group>
            </Stage>
            {snap.mode && (
                <TransformControls
                    object={selectionGroupRef.current ?? undefined}
                    mode={snap.mode}
                    onMouseDown={() => (state.cameraControlsEnabled = false)}
                    onMouseUp={() => (state.cameraControlsEnabled = true)}
                />
            )}
        </>
    );
}

function handleControlEnd(): void {
    state.currentAreaSelection = 'other';
}

useGLTF.preload('/3DModels/PPSH41/scene.gltf');
