/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Rotuma (https://sketchfab.com/Rotuma)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mp5-submachine-gun-a73b61932a0e4eecb5db5c63c158aa24
Title: MP5 Submachine Gun
*/

import { useGLTF } from '@react-three/drei';
import { JSX, useMemo } from 'react';
import * as THREE from 'three';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
    nodes: {
        Bolt_low_low_0: THREE.Mesh;
        Trigger_low_low_0: THREE.Mesh;
        CH_low_low_0: THREE.Mesh;
        Receiver_low_low_0: THREE.Mesh;
        Barrel_low_low_0: THREE.Mesh;
        Stock_low_low_0: THREE.Mesh;
        Mag_low_Maglow_0: THREE.Mesh;
        FS_low_low_0: THREE.Mesh;
    };
    materials: {
        material: THREE.MeshStandardMaterial;
        Maglow: THREE.MeshStandardMaterial;
    };
};

export default function MP5(props: JSX.IntrinsicElements['group']) {
    const { nodes, materials } = useGLTF('/3DModels/MP5/Main/scene.gltf') as unknown as GLTFResult;
    useMemo(() => {
        if (materials.material) {
            if (materials.material.normalMap) {
                materials.material.normalScale.set(0.5, 0.5);
            }
            materials.material.roughness = 0.5;
            materials.material.metalness = 0.8;
        }

        if (materials.Maglow) {
            materials.Maglow.roughness = 0.3;
        }
    }, [materials]);

    return (
        <group {...props} dispose={null} scale={15} position={[0, -10, 0]} rotation={[0, Math.PI / 2, 0]}>
            <group name="Sketchfab_Scene">
                <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
                    <group name="MP5fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
                        <group name="RootNode">
                            <group name="LowTri2" position={[0, -0.151, -0.134]}>
                                <group name="Bolt_low">
                                    <mesh
                                        name="Bolt_low_low_0"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Bolt_low_low_0.geometry}
                                        material={materials.material}
                                    />
                                </group>
                                <group name="Trigger_low">
                                    <mesh
                                        name="Trigger_low_low_0"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Trigger_low_low_0.geometry}
                                        material={materials.material}
                                    />
                                </group>
                                <group name="CH_low">
                                    <mesh
                                        name="CH_low_low_0"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.CH_low_low_0.geometry}
                                        material={materials.material}
                                    />
                                </group>
                                <group name="Receiver_low">
                                    <mesh
                                        name="Receiver_low_low_0"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Receiver_low_low_0.geometry}
                                        material={materials.material}
                                    />
                                </group>
                                <group name="Barrel_low">
                                    <mesh
                                        name="Barrel_low_low_0"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Barrel_low_low_0.geometry}
                                        material={materials.material}
                                    />
                                </group>
                                <group name="Stock_low">
                                    <mesh
                                        name="Stock_low_low_0"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Stock_low_low_0.geometry}
                                        material={materials.material}
                                    />
                                </group>
                                <group name="Mag_low">
                                    <mesh
                                        name="Mag_low_Maglow_0"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Mag_low_Maglow_0.geometry}
                                        material={materials.Maglow}
                                    />
                                </group>
                                <group name="FS_low">
                                    <mesh
                                        name="FS_low_low_0"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.FS_low_low_0.geometry}
                                        material={materials.material}
                                    />
                                </group>
                            </group>
                        </group>
                    </group>
                </group>
            </group>
        </group>
    );
}

useGLTF.preload('/3DModels/MP5/main/scene.gltf');
