/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: MCTav1sh (https://sketchfab.com/MCTav1sh)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ppsh-41-tactical-d7d785b781a94df5b9a4956f64bc3e93
Title: PPSH-41 TACTICAL
*/

import { useGLTF } from '@react-three/drei';
import { JSX, useMemo } from 'react';
import * as THREE from 'three';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
    nodes: {
        defaultMaterial: THREE.Mesh;
        defaultMaterial_1: THREE.Mesh;
        defaultMaterial_2: THREE.Mesh;
        defaultMaterial_3: THREE.Mesh;
        defaultMaterial_4: THREE.Mesh;
        defaultMaterial_5: THREE.Mesh;
        defaultMaterial_6: THREE.Mesh;
        defaultMaterial_7: THREE.Mesh;
        defaultMaterial_8: THREE.Mesh;
        defaultMaterial_9: THREE.Mesh;
        defaultMaterial_10: THREE.Mesh;
        defaultMaterial_11: THREE.Mesh;
        defaultMaterial_12: THREE.Mesh;
        defaultMaterial_13: THREE.Mesh;
        defaultMaterial_14: THREE.Mesh;
        defaultMaterial_15: THREE.Mesh;
        defaultMaterial_16: THREE.Mesh;
        defaultMaterial_17: THREE.Mesh;
        defaultMaterial_18: THREE.Mesh;
        defaultMaterial_19: THREE.Mesh;
        defaultMaterial_20: THREE.Mesh;
        defaultMaterial_21: THREE.Mesh;
        defaultMaterial_22: THREE.Mesh;
        defaultMaterial_23: THREE.Mesh;
        defaultMaterial_24: THREE.Mesh;
        defaultMaterial_25: THREE.Mesh;
        defaultMaterial_26: THREE.Mesh;
        defaultMaterial_27: THREE.Mesh;
        defaultMaterial_28: THREE.Mesh;
        defaultMaterial_29: THREE.Mesh;
        defaultMaterial_30: THREE.Mesh;
        defaultMaterial_31: THREE.Mesh;
        defaultMaterial_32: THREE.Mesh;
        defaultMaterial_33: THREE.Mesh;
    };
    materials: {
        perst: THREE.MeshStandardMaterial;
        material_12: THREE.MeshStandardMaterial;
        ammo: THREE.MeshStandardMaterial;
        mag_35: THREE.MeshPhysicalMaterial;
        scope: THREE.MeshStandardMaterial;
        linza: THREE.MeshPhysicalMaterial;
        material: THREE.MeshStandardMaterial;
        text_set: THREE.MeshPhysicalMaterial;
        text_set3: THREE.MeshStandardMaterial;
        text_set2: THREE.MeshPhysicalMaterial;
        text_set1: THREE.MeshPhysicalMaterial;
        texture_set2: THREE.MeshPhysicalMaterial;
        texture_set1: THREE.MeshPhysicalMaterial;
    };
};

export default function Model(props: JSX.IntrinsicElements['group']) {
    const { nodes, materials } = useGLTF('/3DModels/PPSH41/scene.gltf') as unknown as GLTFResult;
    useMemo(() => {
        if (materials.material) {
            if (materials.material.normalMap) {
                materials.material.normalScale.set(0.5, 0.5);
            }
            materials.material.roughness = 0.5;
            materials.material.metalness = 0.8;
        }
    }, [materials]);
    return (
        <group {...props} dispose={null} rotation={[0, Math.PI / 2, 0]} scale={0.115} position={[0.75, 0.25, 0]}>
            <group rotation={[-1.583, -0.175, 0.201]}>
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <group position={[0, 5.011, -11.913]} rotation={[-0.211, 0, 0]} scale={100}>
                        <mesh castShadow receiveShadow geometry={nodes.defaultMaterial_14.geometry} material={materials.linza} />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.defaultMaterial_15.geometry}
                            material={materials.material}
                            position={[0, 0, -0.001]}
                        />
                    </group>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.defaultMaterial.geometry}
                        material={materials.perst}
                        position={[4.404, 1.914, 7.192]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.defaultMaterial_1.geometry}
                        material={materials.perst}
                        position={[4.399, -2.064, 6.142]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.defaultMaterial_2.geometry}
                        material={materials.perst}
                        position={[5.625, -0.408, 9.008]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.defaultMaterial_3.geometry}
                        material={materials.perst}
                        position={[5.542, 2.019, 10.4]}
                        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                        scale={100}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.defaultMaterial_4.geometry}
                        material={materials.perst}
                        position={[-4.926, 1.36, 16.519]}
                        rotation={[-1.589, -1.559, 1.557]}
                        scale={100}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.defaultMaterial_5.geometry}
                        material={materials.perst}
                        position={[4.404, -0.361, -6.925]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.defaultMaterial_6.geometry}
                        material={materials.material_12}
                        position={[4.449, -0.361, -7.12]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.defaultMaterial_7.geometry}
                        material={materials.perst}
                        position={[4.449, -0.361, -6.925]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.defaultMaterial_8.geometry}
                        material={materials.perst}
                        position={[-2.729, 1.98, 10.217]}
                        rotation={[-0.005, 0, 3.13]}
                        scale={100}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.defaultMaterial_9.geometry}
                        material={materials.perst}
                        position={[-3.377, -1.99, 12.799]}
                        rotation={[3.137, 0, -3.13]}
                        scale={100}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.defaultMaterial_10.geometry}
                        material={materials.perst}
                        position={[4.449, -0.376, -6.925]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.defaultMaterial_11.geometry}
                        material={materials.ammo}
                        position={[0, -1.227, -5.667]}
                        rotation={[-0.087, 0, 0]}
                        scale={100}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.defaultMaterial_12.geometry}
                        material={materials.mag_35}
                        position={[0, 0.113, 0.12]}
                        rotation={[-2.268, 0, 0]}
                        scale={100}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.defaultMaterial_13.geometry}
                        material={materials.scope}
                        position={[0, -9.161, -10.393]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.defaultMaterial_16.geometry}
                        material={materials.text_set}
                        position={[0, -0.001, -0.018]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.defaultMaterial_17.geometry}
                        material={materials.text_set}
                        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                        scale={100}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.defaultMaterial_18.geometry}
                        material={materials.text_set3}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.defaultMaterial_19.geometry}
                        material={materials.text_set2}
                        position={[1.04, -4.248, 6.575]}
                        rotation={[-Math.PI / 2, -0.764, 0]}
                        scale={100}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.defaultMaterial_20.geometry}
                        material={materials.text_set3}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.defaultMaterial_21.geometry}
                        material={materials.text_set1}
                        position={[0, -12.323, -28.42]}
                        rotation={[-1.565, 0, 0]}
                        scale={100}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.defaultMaterial_22.geometry}
                        material={materials.text_set1}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.defaultMaterial_23.geometry}
                        material={materials.text_set}
                        position={[0, -0.001, -0.018]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.defaultMaterial_24.geometry}
                        material={materials.texture_set2}
                        position={[0.01, -6.212, -18.837]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.defaultMaterial_25.geometry}
                        material={materials.texture_set2}
                        position={[-0.832, -0.858, -16.299]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.defaultMaterial_26.geometry}
                        material={materials.texture_set1}
                        position={[0.018, -5.698, -20.27]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.defaultMaterial_27.geometry}
                        material={materials.texture_set2}
                        position={[0, -4.865, -8.45]}
                        rotation={[-1.459, 0, 0]}
                        scale={100}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.defaultMaterial_28.geometry}
                        material={materials.texture_set2}
                        position={[0.001, -5.409, -22.562]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.defaultMaterial_29.geometry}
                        material={materials.texture_set2}
                        position={[0, -1.623, -22.88]}
                        scale={100}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.defaultMaterial_30.geometry}
                        material={materials.texture_set1}
                        position={[0, 0.157, -24.379]}
                        rotation={[-Math.PI / 2, 0, -Math.PI]}
                        scale={100}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.defaultMaterial_31.geometry}
                        material={materials.texture_set2}
                        position={[0, -4.35, -16.692]}
                        rotation={[-1.359, 0, 0]}
                        scale={100}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.defaultMaterial_32.geometry}
                        material={materials.texture_set1}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.defaultMaterial_33.geometry}
                        material={materials.texture_set1}
                        position={[-0.014, -0.775, 8.455]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}
                    />
                </group>
            </group>
        </group>
    );
}

useGLTF.preload('/3DModels/PPSH41/scene.gltf');
