/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: MCTav1sh (https://sketchfab.com/MCTav1sh)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ppsh-41-tactical-d7d785b781a94df5b9a4956f64bc3e93
Title: PPSH-41 TACTICAL
*/

import { useCustomizerStore } from '@/stores/useCustomizerStore';
import { Weapon } from '@/types/types';
import { useGLTF } from '@react-three/drei';
import { JSX, useEffect, useMemo } from 'react';
import * as THREE from 'three';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
    nodes: Record<string, THREE.Mesh>;
    materials: {
        perst: THREE.MeshStandardMaterial;
        material_12: THREE.MeshStandardMaterial;
        ammo: THREE.MeshStandardMaterial;
        mag_35: THREE.MeshPhysicalMaterial;
        scope: THREE.MeshStandardMaterial;
        linza: THREE.MeshPhysicalMaterial;
        material: THREE.MeshStandardMaterial;
        text_set: THREE.MeshPhysicalMaterial;
        text_set3: THREE.MeshStandardMaterial;
        text_set2: THREE.MeshPhysicalMaterial;
        text_set1: THREE.MeshPhysicalMaterial;
        texture_set2: THREE.MeshPhysicalMaterial;
        texture_set1: THREE.MeshPhysicalMaterial;
    };
};

type ModelProps = JSX.IntrinsicElements['group'] & {
    weapon: Weapon;
};

export default function Model({ weapon, ...props }: ModelProps) {
    const { nodes, materials, scene } = useGLTF(`/3DModels/${weapon.name}/scene.gltf`) as unknown as GLTFResult;

    const { selected, currentAreaSelection } = useCustomizerStore();

    useEffect(() => {
        const dbAttachmentsToMaterialsObject: Record<string, string> = {};
        dbAttachmentsToMaterialsObject['Foregrip'] = 'defaultMaterial_19';

        Object.values(dbAttachmentsToMaterialsObject).forEach((nodeName) => {
            const n = nodes[nodeName];
            if (n && 'visible' in n) n.visible = false;
        });

        Object.values(selected).forEach((areaAttachmentSelection) => {
            if (!areaAttachmentSelection) return;
            const nodeName = dbAttachmentsToMaterialsObject[areaAttachmentSelection.name];
            const n = nodes[nodeName];
            if (n) n.visible = true;
        });
    }, [currentAreaSelection, nodes, selected]);

    useMemo(() => {
        if (materials.material) {
            if (materials.material.normalMap) {
                materials.material.normalScale.set(0.5, 0.5);
            }
            materials.material.roughness = 0.5;
            materials.material.metalness = 0.8;
        }
    }, [materials]);
    return (
        <group {...props} dispose={null} rotation={[0, Math.PI / 2, 0]} scale={0.115} position={[0.75, 0.25, 0]}>
            <group rotation={[-1.583, -0.175, 0.201]}>
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <primitive object={scene} />
                </group>
            </group>
        </group>
    );
}

useGLTF.preload('/3DModels/PPSH41/scene.gltf');
